name: CI

on: [push, pull_request]

jobs:
  hemtt:
    name: HEMTT
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1

    - name: Build
      run: hemtt build

    - name: Rename build folder
      run: mv .hemttout/build .hemttout/@grad_trenches

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: grad-trenches-${{ github.sha }}
        path: .hemttout/@*
